update tsconfig and package for npm package importability
=== THE STEPS THAT WORK ===

thanks to
https://www.tsmean.com/articles/how-to-write-a-typescript-library/

looks like as of this commit, it will work via
```
yarn add .../path/to/this/repo
```

but `dist` will not be created upon install. so you must then

```
parent-project $ cd node_modules/transtrictor
$ tsc
$ cd -
```

and that seems to work

=== OTHER NON-WORKING NOTES ===

if you change tsconfig to use `"module": "es2020"`
you also need to add `"moduleResolution": "node"`
because without it, you get
```
tsconfig.json:7:9 - error TS5070: Option '--resolveJsonModule' cannot be specified without 'node' module resolution strategy.
```