update tsconfig because commonjs bad
also need to add
    "moduleResolution": "node",
after changing "module" to es2020 because without it, you get
```
tsconfig.json:7:9 - error TS5070: Option '--resolveJsonModule' cannot be specified without 'node' module resolution strategy.
```